update, add groups

diff --git a/frac/lib/initcpio/functions b/frac/lib/initcpio/functions
--- a/frac/lib/initcpio/functions
+++ b/frac/lib/initcpio/functions
@@ -1,35 +1,52 @@
-msg () { [ "${QUIET}" = "n" ] && echo $@; }
-err () { echo "ERROR: $@" >&2; }
-die () { echo "FATAL: $@" >&2; cleanup; exit 1; }
+#!/bin/bash
 
-get_dirname ()
-{
+plain() {
+    local mesg=$1; shift
+    printf "$BOLD    $mesg$NC\n" "$@" >&1
+}
+
+msg() {
+    local mesg=$1; shift
+    printf "$GREEN==>$NC$BOLD $mesg$NC\n" "$@" >&1
+}
+
+msg2() {
+    local mesg=$1; shift
+    printf "$BLUE  ->$NC$BOLD $mesg$NC\n" "$@" >&1
+}
+
+warning() {
+    local mesg=$1; shift
+    printf "$YELLOW==> WARNING:$NC$BOLD $mesg$NC\n" "$@" >&2
+}
+
+error() {
+    local mesg=$1; shift
+    printf "$RED==> ERROR:$NC$BOLD $mesg$NC\n" "$@" >&2
+}
+
+die() {
+  error "$@"
+  cleanup
+  exit 1
+}
+
+get_dirname() {
     # strip any trailing slash first...
     local dir="${1%/}"
     # then get the directory portion
     echo "${dir%/*}"
 }
 
-get_basename ()
-{
+get_basename() {
     echo "${1##*/}"
 }
 
-get_module_name ()
-{
-    #cleanup - remove .ko, replace - with _
-    local modname="${1%.gz}"
-    modname=$(get_basename "${modname%.ko}")
-    modname="${modname//-/_}"
-    echo "$modname"
-}
-
-##
-#  usage : in_array( $needle, $haystack )
-# return : 0 - found
-#          1 - not found
-##
 in_array() {
+    # Search for an element in an array.
+    #   $1: needle
+    #   ${@:2}: haystack
+
     local needle=$1; shift
     [[ -z $1 ]] && return 1 # Not Found
     local item
@@ -39,19 +56,30 @@ in_array() {
     return 1 # Not Found
 }
 
-auto_modules ()
-{
+kmodinfo() {
+    # A wrapper around modinfo, which is aware of our $BASEDIR and
+    # $KERNELVERSION
+    #   $@: args to modinfo
+
+    modinfo -b "$BASEDIR" -k "$KERNELVERSION" "$@" 2>/dev/null
+}
+
+auto_modules() {
+    # Perform auto detection of modules via sysfs.
+
     IFS=$'\n' read -rd '' -a mods < \
         <(find /sys/devices -name modalias -exec sort -zu {} + |
-        xargs -0 modprobe -aRS "$KERNELVERSION" |
+        xargs -0 modprobe -d "$BASEDIR" -aRS "$KERNELVERSION" |
         sort -u)
 
     printf "%s\n" "${mods[@]//-/_}"
     (( ${#mods[*]} ))
 }
 
-all_modules ()
-{
+all_modules() {
+    # Add modules to the initcpio, filtered by grep.
+    #   $@: filter arguments to grep
+
     local -i count=0
     while read -r -d '' mod; do
         (( ++count ))
@@ -63,8 +91,11 @@ all_modules ()
     (( count ))
 }
 
-checked_modules ()
-{
+checked_modules() {
+    # Add modules to the initcpio, filtered by the list of autodetected
+    # modules.
+    #   $@: arguments to all_modules
+
     if [[ -s "$MODULE_FILE" ]]; then
         grep -xFf "$MODULE_FILE" <(all_modules "$@")
         return 1
@@ -73,221 +104,210 @@ checked_modules ()
     fi
 }
 
-add_full_dir ()
-{
-    if [ -n "${1}" -a -d "${1}" ]; then
-        for f in ${1}/*; do
-            if [ -d "${f}" ]; then
-                add_full_dir "${f}"
+add_full_dir() {
+    # Add a directory and all its contents, recursively, to the initcpio image.
+    # No parsing is performed and the contents of the directory is added as is.
+    #   $1: path to directory
+
+    if [[ -n $1 && -d $1 ]]; then
+        for f in "$1"/*; do
+            if [[ -d "$f" ]]; then
+                add_full_dir "$f"
             else
-                add_file "${f}"
+                add_file "$f"
             fi
         done
     fi
 }
 
-add_dir ()
-{
-    #skip root directory and "." for relative directories... i.e. /foo/bar/./blah
-    if [ -n "${1}" -a "${1}" != "/" -a "${1}" != "." ]; then
-        if ! grep -q "dir ${1} " "${FILELIST}"; then
-            add_dir $(get_dirname "${1}")
-            msg "  adding  dir ${1}"
-            echo "dir ${1} 755 0 0" >> "${FILELIST}"
-        fi
-    fi
+add_dir() {
+    # Add a directory to the initcpio image.
+    #   $1: absolute path of directory on image
+
+    (( ! $# )) && return 1
+
+    local path=$1 mode=${2:-755}
+
+    _add_dir "$path" "$mode"
 }
 
-# add_device /dev/foo type major minor [permissions]
-add_device ()
-{
-    if [ $# -ge 4 ]; then
-        local perms
-        perms="${5:-644}"
-        if ! grep -q "nod ${1}" "${FILELIST}"; then
-            add_dir $(get_dirname "${1}")
-            msg "  adding node ${1}"
-            echo "nod ${1} ${perms} 0 0 ${2} ${3} ${4}" >> "${FILELIST}"
-        fi
-    else
-        err "invalid device node format: $@"
+add_symlink() {
+    # Add a symlink to the initcpio image.
+    #   $1: pathname of symlink on image
+    #   $2: absolute path to target of symlink
+
+    (( $# == 2 )) || return 1
+
+    _add_dir "$(get_dirname "$1")"
+    _add_symlink "$2" "$1"
+}
+
+add_file() {
+    # Add a plain file to the initcpio image. No parsing is performed and only
+    # the singular file is added.
+    #   $1: path to file
+    #   $2: destination on initcpio (optional, defaults to same as source)
+
+    (( $# )) || return 1
+
+    # determine source and destination
+    local src= dest=${2:-$1} mode=
+
+    src=$BASEDIR$1
+
+    [[ -f "$src" ]] || { error "$src: No such file"; return 1; }
+
+    mode=$(stat -c %a "$src")
+    if [[ -z "$mode" ]]; then
+        error "failed to stat file: \`$src'"
         return 1
     fi
+
+    _add_file "${dest#$BASEDIR}" "$src" "$mode"
 }
 
-# what the hell does this do?
-add_symlink ()
-{
-    local fil dest dir
-    if [ -h ${1} ]; then
-        fil="${1##$BASEDIR}"
-        dest="${2##$BASEDIR}"
-        add_dir $(get_dirname "${dest}")
-        add_dir $(get_dirname "${fil}")
-        if ! grep -q "slink ${fil} " "${FILELIST}"; then
-            msg "  adding link ${fil} -> ${dest}"
-            echo "slink ${fil} ${dest} $(stat -c '%a' ${1}) 0 0" >> "${FILELIST}"
-        fi
+add_module() {
+    # Add a kernel module to the initcpio image. Dependencies will be
+    # discovered and added.
+    #   $1: module name
+
+    local module path fw dep deps
+    module=${1%.ko*}
+
+    # skip expensive stuff if this module has already been added
+    in_array "${module//-/_}" "${ADDED_MODULES[@]}" && return
+
+    path=$(kmodinfo -0F filename "$module")
+    if [[ $path ]]; then
+        # get module firmware
+        while read -r -d '' fw; do
+            if [[ -e "$BASEDIR/lib/firmware/$fw" ]]; then
+                add_file "/lib/firmware/$fw"
+            fi
+        done < <(kmodinfo -0F firmware "$module")
+
+        # get module depends
+        IFS=',' read -r -d '' -a deps < <(kmodinfo -0F depends "$module")
+        for dep in "${deps[@]}"; do
+            add_module "$dep"
+        done
+
+        ADDED_MODULES+=("${module//-/_}")
+        add_file "${path#$BASEDIR}" || return
+    else
+        error "module '$module' not found"
+        return 1
     fi
-    #fail quietly
+
+    # explicit module depends
+    case "$module" in
+        fat) add_module "nls_cp437" ;;
+        ocfs2) add_module "configfs" ;;
+        libcrc32c) add_module "crc32c"; add_module "crc32c_intel" ;;
+    esac
 }
 
-add_symlink2 ()
-{
-    add_dir $(get_dirname ${1})
-    add_dir $(get_dirname ${2})
-    if ! grep -q "slink ${1} " "${FILELIST}"; then
-         msg "  adding link ${1} -> ${2}"
-         echo "slink ${1} ${2} 777 0 0" >> "${FILELIST}"
-    fi
+_ldd() {
+    LD_TRACE_LOADED_OBJECTS=1 "$LD_SO" "$@"
 }
 
-add_file ()
-{
-    local fil lnk dir dest
-    if [ -f "${1}" ]; then
-        fil="${1}"
-        lnk=$(readlink -f "${fil}")
-        if [ -n "${lnk}" ]; then
-            add_symlink "${fil}" "${lnk}"
-            fil="${lnk}"
-        fi
-        if [ $# -eq 2 ]; then
-            dest="${2}"
-        else
-            dest="${fil##$BASEDIR}"
-            if [ "${dest}" = "${dest#/}" ]; then
-                dest="/${dest}"
+_add_file() {
+  # add a file to $BUILDROOT
+  #   $1: pathname on initcpio
+  #   $2: source on disk
+  #   $3: mode
+
+  (( $# == 3 )) || return $EINVAL
+  [[ -e "$BUILDROOT$1" ]] && return $EEXIST
+
+  (( QUIET )) || plain "adding file: %s" "$1"
+  command install -Dm$3 "$2" "$BUILDROOT$1"
+}
+
+_add_dir() {
+  # add a directory (with parents) to $BUILDROOT
+  #   $1: pathname on initcpio
+  #   $2: mode
+
+    (( $# == 2 )) || [[ "$1" == /?* ]] || return 1 # bad args
+    [[ -e "$BUILDROOT$1" ]] && return 0 # file exists
+
+    (( QUIET )) || plain "adding dir: %s" "$1"
+    command install -dm$2 "$BUILDROOT$1"
+}
+
+_add_symlink() {
+  # add a symlink to $buildroot
+  #   $1: name on initcpio
+  #   $2: target of $1
+
+  (( $# == 2 )) || return $EINVAL
+  [[ -L "$BUILDROOT$1" ]] && return $EEXIST
+
+  (( QUIET )) || plain "adding symlink: %s -> %s" "$2" "$1"
+  ln -s "$2" "$BUILDROOT$1"
+}
+
+add_binary() {
+    # add a binary file to the initcpio image. library dependencies will
+    # be discovered and added.
+    #   $1: path to binary
+    #   $2: destination on initcpio (optional, defaults to same as source)
+
+    local -a sodeps
+    local regex binary dest mode sodep resolved dirname
+
+    binary=$BASEDIR$1
+
+    [[ -f "$binary" ]] || { error "$binary not found"; return 1; }
+
+    dest=${2:-$binary}
+    mode=$(stat -c %a "$binary")
+
+    # always add the binary itself
+    _add_file "${dest#$BASEDIR}" "$binary" "$mode"
+
+    $LD_SO --verify "$binary" &>/dev/null || return # not a binary!
+
+    # resolve sodeps
+    regex='^[[:space:]]*[^/].+ => (.*) \(.*\)'
+    while read line; do
+        [[ "$line" =~ $regex ]] && sodep=${BASH_REMATCH[1]} || continue
+
+        if [[ -f "$sodep" ]]; then # -f follows symlinks, don't believe it!
+            if [[ ! -L $sodep ]]; then
+                _add_file "$sodep" "$BASEDIR$sodep" "$(stat -c %a "$sodep")"
+            else
+                resolved=$(readlink -e "$BASEDIR$sodep")
+                dirname=${resolved%/*}
+                _add_dir "${dirname#$BASEDIR}" 755
+                _add_symlink "$sodep" "${resolved#$BASEDIR}"
+                _add_file "${resolved#$BASEDIR}" "$resolved" 755
             fi
         fi
-
-        add_dir $(get_dirname "${dest}")
-
-        if ! grep -q "file ${dest} " "${FILELIST}"; then
-            msg "  adding file ${dest}"
-            echo "file ${dest} ${fil} $(stat -c '%a' ${fil}) 0 0" >> "${FILELIST}"
-        fi
-    else
-        err "file '${1}' does not exist"
-        return 1
-    fi
+    done < <(_ldd "$binary")
 }
 
-HAS_MODULES="n"
-declare -a ADDED_MODULES
-#modules are handled specially in order to enable autodetection
-add_module ()
-{
-    local m fil path fw mod deps
-    m=$(get_module_name "${1}")
-    #find pattern - replace _ with [-_] to match either
-    fil="${m//_/[-_]}"
+parse_hook() {
+    # parse key global variables set by install hooks. This function is called
+    # prior to the start of hook processing, and after each hook's build
+    # function is run.
 
-    #skip expensive stuff if this module has already been added
-    if in_array $m ${ADDED_MODULES[@]}; then
-        msg "module $m was already added"
-        return
-    fi
+    local item
 
-    found=0
-    for path in $(find "${MODULEDIR}" -type f -name "${fil}.ko" -or -name "${fil}.ko.gz"); do
-        #get needed firmware files
-        for fw in $(/sbin/modinfo -F firmware "${path}"); do
-            [ -f "/lib/firmware/$fw" ] && add_file "/lib/firmware/$fw"
-        done
-        #get module depends
-        deps="$(/sbin/modinfo -F depends "${path}")"
-        for mod in ${deps//,/ }; do
-            if [ -n "${mod}" ]; then
-                add_module "${mod}"
-            fi
-        done
-        HAS_MODULES="y"
-        ADDED_MODULES[${#ADDED_MODULES[*]}]="$m"
-        msg "  adding module ${fil}"
-        add_file "${path}" && found=1
+    for item in $MODULES; do
+        add_module "$item"
     done
-    if [ ${found} -eq 1 ]; then
-        #explicit module depends
-        case "$m" in 
-            fat) add_module "nls_cp437" ;;
-            ocfs2) add_module "configfs" ;;
-            libcrc32c) add_module "crc32c"; add_module "crc32c_intel" ;;
-        esac
-    else
-        err "module '$m' not found"
-    fi
+
+    for item in $BINARIES; do
+        add_binary "$item"
+    done
+
+    for item in $FILES; do
+        add_file "$item"
+    done
+
+    [[ $SCRIPT ]] && add_file "$HOOKDIR/$SCRIPT" "/hooks/$SCRIPT"
 }
 
-add_binary ()
-{
-    local bin dest type lib
-    bin=$(which "${1}")
-    if [ $? -ne 0 ]; then
-        bin="${1}"
-    fi
-
-    dest=""
-    if [ $# -eq 2 ]; then
-        dest=${2}
-    fi
-
-    if [ ! -f "${bin}" ]; then
-        err "'${bin}' is not a file"
-        return 1
-    fi
-
-    if [ $? -eq 0 ]; then
-        type=$(file -b "${bin}")
-        case "${type}" in
-            *script*)
-            msg "   adding '${type}' script, ensure proper interp exists..."
-            add_file "${bin}" ${dest}
-            ;;
-            *executable*|*shared\ object*|*symbolic\ link*)
-            add_file "${bin}" ${dest}
-            #note, this will also handle 'not a dynamic executable' spit out by
-            # static binaries... the deps will produce nothing
-            for lib in $(ldd ${bin} 2>/dev/null | sed "s|.*=>\(.*\)|\1|"); do
-                if [ -n "${lib}" ]; then
-                    #remove TLS libraries
-                    notls=$(echo ${lib} | sed 's|/lib/tls.*/\(lib.*\)|/lib/\1|')
-                    [ -e "${notls}" ] && lib="${notls}"
-                    [ -f "${lib}" ] && add_file "${lib}"
-                fi
-            done
-            ;;
-            *)
-            err "unknown type '${type}' for binary '${bin}'"
-            return 1
-            ;;
-        esac
-    fi
-}
-
-parse_hook ()
-{
-    local mod bin fil
-    for mod in ${MODULES}; do
-        if [ -n "${mod}" ]; then
-            add_module "${mod}"
-        fi
-    done
-
-    for bin in ${BINARIES}; do
-        if [ -n "${bin}" ]; then
-            add_binary "${bin}"
-        fi
-    done
-
-    for fil in ${FILES}; do
-        if [ -n "${fil}" ]; then
-            add_file "${fil}"
-        fi
-    done
-
-    if [ -n "${SCRIPT}" ]; then
-        add_file "${HOOKDIR}/${SCRIPT}" "/hooks/${SCRIPT}"
-    fi
-}
 # vim: set ft=sh ts=4 sw=4 et:
diff --git a/frac/sbin/mkinitcpio b/frac/sbin/mkinitcpio
--- a/frac/sbin/mkinitcpio
+++ b/frac/sbin/mkinitcpio
@@ -10,67 +10,67 @@
 #   in case of embedded spaces, quote all path names and string comparisons
 #
 
+shopt -s extglob
 
 # Settings
-TMPDIR="$(mktemp -d /tmp/mkinitcpio.XXXXXX)"
-BASEDIR=""
-FILELIST="${TMPDIR}/filelist"
-MESSAGEFILE="${TMPDIR}/message"
-KERNELVERSION="$(uname -r)"
-FUNCTIONS="/lib/initcpio/functions"
-CONFIG="/etc/mkinitcpio.conf"
-HOOKDIR="/lib/initcpio/hooks"
-INSTDIR="/lib/initcpio/install"
-MODULE_FILE=""
-SAVELIST=""
-GENIMG=""
-APPEND=""
-PRESET=""
-MESSAGE=""
-SKIPHOOKS=()
-PRESETDIR="/etc/mkinitcpio.d"
-QUIET="y"
-SHOW_AUTOMODS="n"
-COMPRESSION="gzip"
-COMPRESSION_OPTIONS=""
+KERNELVERSION=$(uname -r)
+CARCH=$(uname -m)
+FUNCTIONS=/lib/initcpio/functions
+CONFIG=/etc/mkinitcpio.conf
+HOOKDIR=/lib/initcpio/hooks
+INSTDIR=/lib/initcpio/install
+PRESETDIR=/etc/mkinitcpio.d
+COMPRESSION=gzip
 
-if [ ! $UID ]; then
-    UID=$(id -u)
-fi
+declare TMPDIR BASEDIR MODULE_FILE GENIMG PRESET COMPRESSION_OPTIONS BUILDROOT LD_SO
+declare NC= BOLD= BLUE= GREEN= RED= YELLOW=
+declare -i QUIET=1 SHOW_AUTOMODS=0 SAVELIST=0 COLOR=1
+declare -a SKIPHOOKS ADDED_MODULES
 
 # Add /{,usr}/sbin to path
 # works around undetected problems like in #8448
-PATH="${PATH}:/sbin:/usr/sbin"
+PATH=$PATH:/sbin:/usr/sbin
 # Sanitize environment further
 # GREP_OPTIONS="--color=always" will break everything
 unset GREP_OPTIONS
 
-APPNAME=$(basename "${0}")
+APPNAME=${0##*/}
 
-usage ()
-{
-    echo "${APPNAME}: usage"
-    echo "  -c CONFIG        Use CONFIG file. default: /etc/mkinitcpio.conf"
-    echo "  -k KERNELVERSION Use KERNELVERSION. default: $(uname -r)"
-    echo "  -s NAME          Save filelist. default: no"
-    echo "  -b BASEDIR       Use BASEDIR. default: /"
-    echo "  -g IMAGE         Generate a cpio image as IMAGE. default: no"
-    echo "  -a NAME          Append to an existing filelist. default: no"
-    echo "  -p PRESET        Build specified preset."
-    echo "  -m MESSAGE       Print MESSAGE before passing control to init."
-    echo "  -S SKIPHOOKS     Skip SKIPHOOKS (comma-separated) when building the image."
-    echo "  -v               Verbose output. Default: no"
-    echo "  -M               Display modules found via autodetection." 
-    echo "  -L               List all available hooks." 
-    echo "  -H HOOKNAME      Output help for hook 'HOOKNAME'."
-    echo "  -h               This message."
+usage() {
+    cat <<EOF
+usage: $APPNAME [options]
+
+  Options:
+   -b BASEDIR       Use BASEDIR. default: /
+   -c CONFIG        Use CONFIG file. default: /etc/mkinitcpio.conf
+   -g IMAGE         Generate a cpio image as IMAGE. default: no
+   -H HOOKNAME      Output help for hook 'HOOKNAME'.
+   -h               Display this message.
+   -k KERNELVERSION Use KERNELVERSION. default: $(uname -r)
+   -L               List all available hooks.
+   -M               Display modules found via autodetection.
+   -n               Disable colorized output messages.
+   -p PRESET        Build specified preset from /etc/mkinitcpio.d
+   -S SKIPHOOKS     Skip SKIPHOOKS (comma-separated) when building the image.
+   -s               Save build directory. default: no
+   -t TMPDIR        Use TMPDIR as the temporary build directory.
+   -v               Verbose output. Default: no.
+   -z COMPRESS      Use COMPRESS on resulting image
+
+EOF
     cleanup
     exit 1
 }
 
 cleanup ()
 {
-    [ -n "${TMPDIR}" -a -d "${TMPDIR}" ] && rm -rf ${TMPDIR}
+    if [[ $TMPDIR ]]; then
+        if (( $SAVELIST )); then
+            msg "build directory saved in %s" "$TMPDIR"
+        else
+            rm -rf "$TMPDIR"
+        fi
+    fi
 }
 
 sighandler() {
@@ -78,232 +78,315 @@ sighandler() {
     exit 1
 }
 
+get_kernver() {
+    local kernel=$1
+
+    if [[ "${kernel:0:1}" != / ]]; then
+        echo $kernel
+        return 0
+    fi
+
+    [[ -r "$kernel" ]] || return 1
+
+    read _ kernver < <(file -b "$BASEDIR$kernel" | grep -o 'version [^ ]\+')
+    if [[ "$kernver" && -e "$BASEDIR/lib/modules/$kernver" ]]; then
+        echo "$kernver"
+        return 0
+    fi
+
+    return 1
+}
+
+. "$FUNCTIONS"
+
 trap sighandler TERM INT
 
-while getopts ':c:k:s:b:g:a:p:m:vH:LMhS:' arg; do
-    if [ "${OPTARG#-}" != "${OPTARG}" ]; then
-        echo "error: optional argument to '-${arg}' begins with a '-'"
-        echo "  you probably don't want this....aborting."
-        usage
-    fi
+while getopts ':c:k:sb:g:p:m:nvH:LMhS:t:z:' arg; do
     case "${arg}" in
         c) CONFIG="${OPTARG}" ;;
-        k) KERNELVERSION="${OPTARG}" ;;
-        s) SAVELIST="y"; FILELIST="${OPTARG}" ;;
+        k) optkver=$OPTARG ;;
+        s) SAVELIST=1; ;;
         b) BASEDIR="${OPTARG}" ;;
         g) GENIMG="${OPTARG}" ;;
-        a) APPEND="y"; SAVELIST="y"; FILELIST="${OPTARG}" ;;
+        h) usage ;;
         p) PRESET="${OPTARG}" ;;
-        m) MESSAGE="${OPTARG}" ;;
-        v) QUIET="n" ;;
+        n) COLOR=0 ;;
+        v) QUIET=0 ;;
         S) OLDIFS=${IFS}
            IFS=,
            SKIPHOOKS=(${OPTARG})
            IFS=${OLDIFS}
            unset OLDIFS
            ;;
-        H) . "${INSTDIR}/${OPTARG}";
+        H) if [[ ! -r "${INSTDIR}/${OPTARG}" ]]; then
+               error "No hook ${OPTARG}"
+               exit 1
+           fi
+           . "${INSTDIR}/${OPTARG}"
+           if [[ $(type -t help) != function ]]; then
+               error "No help for hook ${OPTARG}"
+               exit 1
+           fi
            echo "Help for hook '${OPTARG}':"
            help
-           cleanup
            exit 0 ;;
-        L) echo "Available hooks: " 
-           for h in ${INSTDIR}/*; do
-               echo "   $(basename ${h})"
-           done
-           cleanup
+        L) msg "Available hooks"
+           cd "$INSTDIR" >/dev/null
+           printf '   %s\n' * | column -c$(tput cols)
            exit 0 ;;
-        M) SHOW_AUTOMODS="y" ;;
-        h|?) usage ;;
-        :) echo "${OPTARG} requires a value..."; usage ;;
-        *) echo "invalid argument '${arg}'"; usage ;;
+        M) SHOW_AUTOMODS=1 ;;
+        t) TMPDIR=$OPTARG ;;
+        z) optcompress=$OPTARG ;;
+        :) error "option requires an argument -- '$OPTARG'" >&2
+           exit 1 ;;
+       \?) error "invalid option -- '$OPTARG'" >&2
+           exit 1 ;;
     esac
 done
-shift $((${OPTIND} - 1))
+shift $((OPTIND - 1))
+
+if [[ -t 2 ]] && (( COLOR )); then
+    # prefer terminal safe colored and bold text when tput is supported
+    if tput setaf 0 &>/dev/null; then
+        NC="$(tput sgr0)"
+        BOLD="$(tput bold)"
+        BLUE="$BOLD$(tput setaf 4)"
+        GREEN="$BOLD$(tput setaf 2)"
+        RED="$BOLD$(tput setaf 1)"
+        YELLOW="$BOLD$(tput setaf 3)"
+    else
+        NC="\e[1;0m"
+        BOLD="\e[1;1m"
+        BLUE="$BOLD\e[1;34m"
+        GREEN="$BOLD\e[1;32m"
+        RED="$BOLD\e[1;31m"
+        YELLOW="$BOLD\e[1;33m"
+    fi
+fi
+readonly NC BOLD BLUE GREEN RED YELLOW
+
+if [[ $optkver ]]; then
+    if ! KERNELVERSION=$(get_kernver "$optkver"); then
+         die "'$optkver' is an invalid kernel specifier"
+    fi
+fi
+
+if [[ $TMPDIR ]]; then
+    if [[ ! -d $TMPDIR ]]; then
+        error "'$TMPDIR' does not exist or is not a directory"
+        unset TMPDIR
+        cleanup
+        exit 1
+    fi
+fi
+TMPDIR=$(mktemp -d "${TMPDIR:-/tmp}/mkinitcpio.XXXXXX")
+declare BUILDROOT=$TMPDIR/root
 
 # use preset $PRESET
-if [ -n "${PRESET}" ]; then
-    if [ -f "${PRESETDIR}/${PRESET}.preset" ]; then
+if [[ $PRESET ]]; then
+    # allow absolute path to preset file, else resolve it
+    if [[ "${PRESET:0:1}" != '/' ]]; then
+        printf -v PRESET '%s/%s.preset' "$PRESETDIR" "$PRESET"
+    fi
+    if [[ -f "$PRESET" ]]; then
         # Use -b, -m and -v options specified earlier
-        PRESET_MKOPTS="${0}"
-        [ -n "${BASEDIR}" ] && PRESET_MKOPTS="${PRESET_MKOPTS} -b ${BASEDIR}"
-        [ -n "${MESSAGE}" ] && PRESET_MKOPTS="${PRESET_MKOPTS} -m \"${MESSAGE}\""
-        [ "${QUIET}" = "n" ] && PRESET_MKOPTS="${PRESET_MKOPTS} -v"
+        declare -a preset_mkopts preset_cmd
+        [[ $BASEDIR ]] && preset_mkopts+=(-b "$BASEDIR")
+        (( QUIET )) || preset_mkopts+=(-v)
         # Build all images
-        . ${PRESETDIR}/${PRESET}.preset
-        for p in ${PRESETS[@]}; do
-            echo "==> Building image \"${p}\""
-            PRESET_CMD="${PRESET_MKOPTS}"
+        . "$PRESET"
+        for p in "${PRESETS[@]}"; do
+            msg "Building image from preset: '$p'"
+            preset_cmd=("${preset_mkopts[@]}")
 
-            eval "PRESET_KVER=\"\${${p}_kver}\""
-            [ -z "${PRESET_KVER}" ] && PRESET_KVER="${ALL_kver}"
-            eval "PRESET_CONFIG=\"\${${p}_config}\""
-            [ -z "${PRESET_CONFIG}" ] && PRESET_CONFIG="${ALL_config}"
-            eval "PRESET_IMAGE=\"\${${p}_image}\""
-            eval "PRESET_OPTIONS=\"\${${p}_options}\""
-
-            if [ -n "${PRESET_KVER}" ]; then
-                PRESET_CMD="${PRESET_CMD} -k ${PRESET_KVER}"
+            preset_kver=${p}_kver
+            if [[ ${!preset_kver:-$ALL_kver} ]]; then
+                preset_cmd+=(-k "${!preset_kver:-$ALL_kver}")
             else
-                echo "==> No kernel version specified. Skipping image \"${p}\"."
+                warning "No kernel version specified. Skipping image '%s'" "$p"
                 continue
             fi
 
-            if [ -n "${PRESET_CONFIG}" ]; then
-                PRESET_CMD="${PRESET_CMD} -c ${PRESET_CONFIG}"
+            preset_config=${p}_config
+            if [[ ${!preset_config:-$ALL_config} ]]; then
+              preset_cmd+=(-c "$BASEDIR${!preset_config:-$ALL_config}")
             else
-                echo "==> No configuration file specified. Skipping image \"${p}\"."
+                warning "No configuration file specified. Skipping image '%s'" "$p"
                 continue
             fi
 
-            if [ -n "${PRESET_IMAGE}" ]; then
-                PRESET_CMD="${PRESET_CMD} -g ${PRESET_IMAGE}"
+            preset_image=${p}_image
+            if [[ ${!preset_image} ]]; then
+                preset_cmd+=(-g "$BASEDIR${!preset_image}")
             else
-                echo "==> No image file specified. Skipping image \"${p}\"."
+                warning "No image file specified. Skipping image '%s'" "$p"
                 continue
             fi
 
-            if [ -n "${PRESET_OPTIONS}" ]; then
-                PRESET_CMD="${PRESET_CMD} ${PRESET_OPTIONS}"
+            preset_options=${p}_options
+            if [[ ${!preset_options} ]]; then
+                preset_cmd+=(${!preset_options}) # intentional word splitting
             fi
 
-            echo "==> Running command: ${PRESET_CMD}"
-            if eval ${PRESET_CMD}; then
-                echo "==> SUCCESS"
-            else
-                echo "==> FAIL"
-            fi
+            msg2 "${preset_cmd[*]}"
+            "$0" "${preset_cmd[@]}"
         done
         cleanup
         exit 0
     else
-        echo "Preset ${PRESET} does not exist. Exiting."
-        cleanup
-        exit 1
+        die "Preset $PRESET does not exist. Exiting."
     fi
 fi
 
-# remove trailing / from BASEDIR
-BASEDIR="${BASEDIR%/}"
+if [[ $BASEDIR ]]; then
+    # resolve the path. it might be a relative path and/or contain symlinks
+    abspath=$(readlink -e "$BASEDIR")
+    if [[ -z $abspath ]]; then
+        die "base directory '$BASEDIR' does not exist or is not a directory"
+    fi
+    BASEDIR=$abspath
+    unset abspath
+fi
 
-MODULEDIR="${BASEDIR}/lib/modules/${KERNELVERSION}"
-
-if [ -n "${BASEDIR}" ]; then
-    if [ "${BASEDIR}" = "${BASEDIR#/}" ]; then
-        BASEDIR="$(pwd)/${BASEDIR}"
-    elif [ ! -d "${BASEDIR}" ]; then
-        echo "base directory '${BASEDIR}' does not exist or is not a directory"
-        cleanup
-        exit 1
+if [[ $GENIMG ]]; then
+    IMGPATH=$(readlink -f "$GENIMG")
+    if [[ -z $IMGPATH || ! -w ${IMGPATH%/*} ]]; then
+      die "error: unable to write to path: '$GENIMG'"
     fi
 fi
 
-if [ ! -f "${CONFIG}" ]; then
-    echo "config file '${CONFIG}' cannot be found, aborting..."
-    cleanup
-    exit 1
+if [[ ! -f "$CONFIG" ]]; then
+    die "config file '$CONFIG' cannot be found, aborting..."
 fi
-. "${CONFIG}"
+. "$CONFIG"
 
-if [ -f "${FILELIST}" -a -z "${APPEND}" ]; then
-    if [ -z "${SAVELIST}" ]; then
-        rm ${FILELIST}
-        touch "${FILELIST}"
-    else
-        echo "destination file list '${FILELIST}' exists - remove before running"
-        cleanup
-        exit 1
-    fi
-else
-    touch "${FILELIST}"
+MODULEDIR=$BASEDIR/lib/modules/$KERNELVERSION
+if [[ ! -d $MODULEDIR ]]; then
+    die "'$MODULEDIR' is not a valid kernel module directory"
 fi
 
-BASEDIR=$(echo ${BASEDIR} | tr -s /)
-MODULEDIR=$(echo ${MODULEDIR} | tr -s /)
-
-. "${FUNCTIONS}"
-
-if [ "${SHOW_AUTOMODS}" = "y" ]; then
-    echo "Modules autodetected:"
+if (( SHOW_AUTOMODS )); then
+    msg "Modules autodetected"
     . "${INSTDIR}/autodetect"
-    install
+    build
     cat "${MODULE_FILE}"
     cleanup
     exit 0
 fi
 
-if [ -z "${GENIMG}" ]; then
-    echo ":: Begin dry run"
+
+if [[ -z $GENIMG ]]; then
+    msg "Starting dry run: %s" "$KERNELVERSION"
 else
-    echo ":: Begin build"
+    COMPRESSION=${optcompress:-$COMPRESSION}
+    if ! type -P "$COMPRESSION" >/dev/null; then
+        die "Unable to locate compression method: %s" "$optcompress"
+    fi
+
+    msg "Starting build: %s" "$KERNELVERSION"
 fi
+
+# set errtrace and a trap to catch errors in parse_hook
+declare -i builderrors=0
+set -E
+trap '[[ $FUNCNAME = parse_hook ]] && (( ++builderrors ))' ERR
+
 #parse 'global' hook, as defined in ${CONFIG}
 parse_hook
 
+# resolve the linker and add it
+case $CARCH in
+  i686) LD_SO=("$BASEDIR"/lib/ld-linux.so.?*) ;;
+  x86_64) LD_SO=("$BASEDIR"/lib/ld-linux-${CARCH//_/-}.so.?*) ;;
+  *) die "unknown architecture: $CARCH" ;;
+esac
+
+if (( ${#LD_SO[*]} != 1 )); then # uh oh...
+  die "failed to resolve the location of /lib/ld.so. Please report this bug."
+fi
+
+resolved=$(readlink -e "$LD_SO")
+_add_file "${resolved#$BASEDIR}" "$resolved" 755
+_add_symlink "${LD_SO#$BASEDIR}" "$resolved"
+unset resolved
+
 for hook in ${HOOKS}; do
-    in_array ${hook} ${SKIPHOOKS[@]} && continue
-    unset MODULES
-    unset BINARIES
-    unset FILES
-    install () { msg "${hook}: no install function..."; }
-    # Deprecation check
-    # A hook is considered deprecated if it is a symlink
-    # within $INSTDIR.
-    if [ -h "${INSTDIR}/${hook}" ]; then
-        newhook="$(readlink -ne "${INSTDIR}/${hook}")"
-        if [ -n "${newhook}" -a "${INSTDIR}/$(get_basename ${newhook})" -ef "${newhook}" ]; then
-            newhook="$(get_basename ${newhook})"
-            echo "   -------------------------------------------------------------------"
-            echo "   WARNING: Hook \"${hook}\" is deprecated."
-            echo "            Replace it with \"${newhook}\" in your configuration file."
-            echo "   -------------------------------------------------------------------"
-            hook="${newhook}"
+    in_array "$hook" "${SKIPHOOKS[@]}" && continue
+    unset MODULES BINARIES FILES SCRIPT
+    build () { error "$hook: no build function..."; }
+
+    # A hook is considered deprecated if it is a symlink within $INSTDIR.
+    if [[ -L "$INSTDIR/$hook" ]]; then
+        newhook=$(readlink -e "$INSTDIR/$hook")
+        if [[ $newhook && "$INSTDIR/${newhook##*/}" -ef "$newhook" ]]; then
+            newhook=${newhook##*/}
+            warning "Hook '%s' is deprecated. Replace it with '%s' in your config" "$hook" "$newhook"
+            hook=$newhook
         fi
     fi
-    if grep -q "install" "${INSTDIR}/${hook}"; then
+    if [[ -r "${INSTDIR}/${hook}" ]]; then
         . "${INSTDIR}/${hook}"
-        echo ":: Parsing hook [${hook}]"
-        install
+        msg2 "Parsing hook: [%s]" "$hook"
+        if [[ $(type -t install) = 'function' ]]; then
+            warning "Hook '%s' uses a deprecated 'install' function. This should be renamed 'build'" "$hook"
+            install
+            unset install
+        else
+            build
+        fi
         parse_hook
     else
-        die "Hook '${hook}' can not be found."
+        die "Hook '$hook' can not be found."
     fi
 done
 
-if [ "${HAS_MODULES}" = "y" ]; then
-    echo ":: Generating module dependencies"
-    # unfortuate name collision between a function and utility program
-    unset install
-    for mod in $(grep "file /lib/modules/${KERNELVERSION}" ${FILELIST} | cut -d' ' -f2); do
-        install -m 644 -D "${BASEDIR}${mod}" "${TMPDIR}${mod}"
-    done
-    /sbin/depmod -b ${TMPDIR} ${KERNELVERSION}
-    for dmfile in modules.{dep,alias,symbols}.bin; do
-        add_file "${TMPDIR}/lib/modules/${KERNELVERSION}/$dmfile" "/lib/modules/${KERNELVERSION}/$dmfile"
-    done
+# unset errtrace and trap
+set +E
+trap ERR
+
+if (( ${#ADDED_MODULES[*]} )); then
+    msg "Generating module dependencies"
+    /sbin/depmod -b "${TMPDIR}/root" "${KERNELVERSION}"
+    rm "$BUILDROOT/lib/modules/$KERNELVERSION"/modules.!(dep.bin|alias.bin|symbols.bin)
 fi
 
-status=0
-if [ -n "${GENIMG}" ]; then
-    echo ":: Generating image '${GENIMG}'"
-    shopt -s -o pipefail
-    [ ${COMPRESSION} = "xz" ] && COMPRESSION_OPTIONS="${COMPRESSION_OPTIONS} --check=crc32"
-    if ! /sbin/gen_init_cpio ${FILELIST} | ${COMPRESSION} ${COMPRESSION_OPTIONS} > "${GENIMG}"; then
-        echo ":: Image generation FAILED"
-        status=1
-    else
-        echo ":: Image generation successful"
-        status=0
+declare -i status=0
+declare -a pipesave
+if [[ "${GENIMG}" ]]; then
+    msg "Creating $COMPRESSION initcpio image: %s" "$GENIMG"
+    [[ "$COMPRESSION" = xz ]] && COMPRESSION_OPTIONS+=" --check=crc32"
+
+    pushd "$BUILDROOT" >/dev/null
+    find . -print0 | bsdcpio -0oH newc | $COMPRESSION $COMPRESSION_OPTIONS > "$IMGPATH"
+    pipesave=("${PIPESTATUS[@]}") # save immediately
+    popd >/dev/null
+
+    if (( pipesave[0] )); then
+        errmsg="find reported an error"
+    elif (( pipesave[1] )); then
+        errmsg="bsdcpio reported an error"
+    elif (( pipesave[2] )); then
+        errmsg="$COMPRESSION reported an error"
     fi
 
-    if [ -z "${SAVELIST}" ]; then
-        rm ${FILELIST}
+    if (( builderrors )); then
+        warning "errors were encountered during the build. The image may not be complete."
+        status=1
     fi
+
+    if [[ $errmsg ]]; then
+        error "Image generation FAILED: %s\n" "$errmsg"
+        status=1
+    else
+        msg "Image generation successful"
+    fi
+
 else
-    echo ":: Dry run complete, use -g IMAGE to generate a real image"
+    msg "Dry run complete, use -g IMAGE to generate a real image"
 fi
 
 cleanup
 
 exit ${status}
-#vim:set ft=sh ts=4 sw=4 noet:
+
+# vim: set ft=sh ts=4 sw=4 et:
