update

diff --git a/frac/lib/initcpio/functions b/frac/lib/initcpio/functions
--- a/frac/lib/initcpio/functions
+++ b/frac/lib/initcpio/functions
@@ -26,9 +26,8 @@ error() {
 }
 
 die() {
-  error "$@"
-  cleanup
-  exit 1
+    error "$@"
+    cleanup 1
 }
 
 get_dirname() {
@@ -47,21 +46,49 @@ in_array() {
     #   $1: needle
     #   ${@:2}: haystack
 
-    local needle=$1; shift
-    [[ -z $1 ]] && return 1 # Not Found
-    local item
+    local item= needle=$1; shift
+
     for item in "$@"; do
         [[ $item = $needle ]] && return 0 # Found
     done
     return 1 # Not Found
 }
 
-kmodinfo() {
-    # A wrapper around modinfo, which is aware of our $BASEDIR and
-    # $KERNELVERSION
-    #   $@: args to modinfo
+_add_file() {
+    # add a file to $BUILDROOT
+    #   $1: pathname on initcpio
+    #   $2: source on disk
+    #   $3: mode
 
-    modinfo -b "$BASEDIR" -k "$KERNELVERSION" "$@" 2>/dev/null
+    (( $# == 3 )) || return $EINVAL
+    [[ -e "$BUILDROOT$1" ]] && return $EEXIST
+
+    (( QUIET )) || plain "adding file: %s" "$1"
+    command install -Dm$3 "$2" "$BUILDROOT$1"
+}
+
+_add_dir() {
+    # add a directory (with parents) to $BUILDROOT
+    #   $1: pathname on initcpio
+    #   $2: mode
+
+    (( $# == 2 )) || [[ "$1" == /?* ]] || return 1 # bad args
+    [[ -e "$BUILDROOT$1" ]] && return 0 # file exists
+
+    (( QUIET )) || plain "adding dir: %s" "$1"
+    command install -dm$2 "$BUILDROOT$1"
+}
+
+_add_symlink() {
+    # add a symlink to $buildroot
+    #   $1: name on initcpio
+    #   $2: target of $1
+
+    (( $# == 2 )) || return $EINVAL
+    [[ -L "$BUILDROOT$1" ]] && return $EEXIST
+
+    (( QUIET )) || plain "adding symlink: %s -> %s" "$2" "$1"
+    ln -s "$2" "$BUILDROOT$1"
 }
 
 auto_modules() {
@@ -102,6 +129,53 @@ checked_modules() {
     else
         all_modules "$@"
     fi
+}
+
+add_module() {
+    # Add a kernel module to the initcpio image. Dependencies will be
+    # discovered and added.
+    #   $1: module name
+
+    local module path dep deps field value
+    module=${1%.ko*}
+
+    # skip expensive stuff if this module has already been added
+    in_array "${module//-/_}" "${ADDED_MODULES[@]}" && return
+
+    while IFS=':= ' read -r -d '' field value; do
+        case "$field" in
+            filename)
+                path=$value
+                ;;
+            depends)
+                IFS=',' read -r -a deps <<< "$value"
+                for dep in "${deps[@]}"; do
+                    add_module "$dep"
+                done
+                ;;
+            firmware)
+                if [[ -e "$BASEDIR/lib/firmware/$value" ]]; then
+                    _add_file "/lib/firmware/$value" "$BASEDIR/lib/firmware/$value" 644
+                fi
+                ;;
+        esac
+    done < <(modinfo -b "$BASEDIR" -k "$KERNELVERSION" -0 "$module" 2>/dev/null)
+
+    if [[ -z $path ]]; then
+        error "module '$module' not found"
+        return 1
+    fi
+
+    # aggregate modules and add them all at once to save some forks
+    MODPATHS+=("$path")
+    ADDED_MODULES+=("${module//-/_}")
+
+    # explicit module depends
+    case "$module" in
+        fat) add_module "nls_cp437" ;;
+        ocfs2) add_module "configfs" ;;
+        libcrc32c) add_module "crc32c"; add_module "crc32c_intel" ;;
+    esac
 }
 
 add_full_dir() {
@@ -166,88 +240,6 @@ add_file() {
     _add_file "${dest#$BASEDIR}" "$src" "$mode"
 }
 
-add_module() {
-    # Add a kernel module to the initcpio image. Dependencies will be
-    # discovered and added.
-    #   $1: module name
-
-    local module path fw dep deps
-    module=${1%.ko*}
-
-    # skip expensive stuff if this module has already been added
-    in_array "${module//-/_}" "${ADDED_MODULES[@]}" && return
-
-    path=$(kmodinfo -0F filename "$module")
-    if [[ $path ]]; then
-        # get module firmware
-        while read -r -d '' fw; do
-            if [[ -e "$BASEDIR/lib/firmware/$fw" ]]; then
-                add_file "/lib/firmware/$fw"
-            fi
-        done < <(kmodinfo -0F firmware "$module")
-
-        # get module depends
-        IFS=',' read -r -d '' -a deps < <(kmodinfo -0F depends "$module")
-        for dep in "${deps[@]}"; do
-            add_module "$dep"
-        done
-
-        ADDED_MODULES+=("${module//-/_}")
-        add_file "${path#$BASEDIR}" || return
-    else
-        error "module '$module' not found"
-        return 1
-    fi
-
-    # explicit module depends
-    case "$module" in
-        fat) add_module "nls_cp437" ;;
-        ocfs2) add_module "configfs" ;;
-        libcrc32c) add_module "crc32c"; add_module "crc32c_intel" ;;
-    esac
-}
-
-_ldd() {
-    LD_TRACE_LOADED_OBJECTS=1 "$LD_SO" "$@"
-}
-
-_add_file() {
-  # add a file to $BUILDROOT
-  #   $1: pathname on initcpio
-  #   $2: source on disk
-  #   $3: mode
-
-  (( $# == 3 )) || return $EINVAL
-  [[ -e "$BUILDROOT$1" ]] && return $EEXIST
-
-  (( QUIET )) || plain "adding file: %s" "$1"
-  command install -Dm$3 "$2" "$BUILDROOT$1"
-}
-
-_add_dir() {
-  # add a directory (with parents) to $BUILDROOT
-  #   $1: pathname on initcpio
-  #   $2: mode
-
-    (( $# == 2 )) || [[ "$1" == /?* ]] || return 1 # bad args
-    [[ -e "$BUILDROOT$1" ]] && return 0 # file exists
-
-    (( QUIET )) || plain "adding dir: %s" "$1"
-    command install -dm$2 "$BUILDROOT$1"
-}
-
-_add_symlink() {
-  # add a symlink to $buildroot
-  #   $1: name on initcpio
-  #   $2: target of $1
-
-  (( $# == 2 )) || return $EINVAL
-  [[ -L "$BUILDROOT$1" ]] && return $EEXIST
-
-  (( QUIET )) || plain "adding symlink: %s -> %s" "$2" "$1"
-  ln -s "$2" "$BUILDROOT$1"
-}
-
 add_binary() {
     # add a binary file to the initcpio image. library dependencies will
     # be discovered and added.
@@ -267,10 +259,10 @@ add_binary() {
     # always add the binary itself
     _add_file "${dest#$BASEDIR}" "$binary" "$mode"
 
-    $LD_SO --verify "$binary" &>/dev/null || return # not a binary!
+    lddout=$(ldd "$binary" 2>/dev/null) || return 1 # not a binary!
 
     # resolve sodeps
-    regex='^[[:space:]]*[^/].+ => (.*) \(.*\)'
+    regex='(/.+) \(0x[a-fA-F0-9]+\)'
     while read line; do
         [[ "$line" =~ $regex ]] && sodep=${BASH_REMATCH[1]} || continue
 
@@ -285,7 +277,9 @@ add_binary() {
                 _add_file "${resolved#$BASEDIR}" "$resolved" 755
             fi
         fi
-    done < <(_ldd "$binary")
+    done <<< "$lddout"
+
+    return 0
 }
 
 parse_hook() {
